<?php

/*
FUNCTION TO CHECK IF USER IS LOGGED INTO SESSION
IT BASICALLY SHORTNERS THE PROCESS OF CHECKING WHETHER SESSION VARIABLE IS SET
I USE ID AND EMAIL TO DOUBLE CHECK IF EVERYTHING IS ALLRIGHT
*/
function is_logged()
{

  if (isset($_SESSION['id']) && isset($_SESSION['email'])) {
    return true;
  } else {
    return false;
  }
}
